spring.application.name=SafeBus
spring.profiles.default=dev
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/safebus;MODE=MySQL;AUTO_SERVER=TRUE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=7MB
safebus.jwt.secret=${SAFEBUS_JWT_SECRET:dev-only-secret-dev-only-secret-dev-only-secret}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
server.port=${PORT:8080}
server.forward-headers-strategy=framework
safebus.jwt.ttl=PT12H
safebus.driver.qr-credential-ttl=P365D
